# Generated by Django 4.1.1 on 2022-10-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_room_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Amenities"},
        ),
        migrations.RenameField(
            model_name="amenity",
            old_name="crated_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="crated_at",
            new_name="created_at",
        ),
    ]
