# Generated by Django 4.1.1 on 2022-10-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_alter_amenity_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="Amenity",
            new_name="amenities",
        ),
    ]
