# Generated by Django 4.1.1 on 2022-10-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="perk",
            old_name="detail",
            new_name="details",
        ),
    ]
