# Generated by Django 4.1.1 on 2022-10-07 10:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("experiences", "0003_experience_category"),
        ("rooms", "0006_room_category"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reviews",
            new_name="Review",
        ),
    ]
